version: "3"
services:
  schatsi_machine_learning_R:
    image: schatsi_machine_learning_r
    volumes:
     - ${INPUT_DIRECTORY}:/input
     - ${OUTPUT_DIRECTORY}:/output
    environment:
      PASSWORD: mypassword
    ports:
      - 8787:8787